# Action to Deploy to Vercel
# envs are:
#   VITE_JOKES_API_BASE_URL=https://api.api-ninjas.com/v1/
#   VITE_JOKES_API_KEY=123xxx
#
# also run:
# npm run lint
# npm run test

name: Deploy to Vercel

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main
    workflow_dispatch:

concurrency:
    group: 'CI/CD'
    cancel-in-progress: true

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '18.16.0'

            - name: Install dependencies
              run: npm install

            - name: Build
              run: npm run build

            - name: Format
              run: npm run format

            - name: Lint
              run: npm run lint

            - name: Test
              run: npm run test

            - name: Deploy to Vercel
              uses: amondnet/vercel-action@v20
              with:
                  vercel-token: ${{ secrets.VERCEL_TOKEN }}
                  vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
                  vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
